directories:
  output: dist-app
  buildResources: build
productName: 으랏차차 작업레츠기릿
appId: com.yourcompany.workletsgirit
mac:
  category: public.app-category.productivity
win:
  target: nsis
files: []
electronVersion: 38.2.0
